server:
  port: 9000
  servlet:
    # 应用的访问路径
    context-path: /starts
spring:
  application:
    name: starts开发平台

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starts?useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 60000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.simba.system.entity

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

starts:
  xss:
    enabled: true
    exclude-fields:
      - noticeContent
    exclude-urls:
      - /system/notice/*
  whitelist:
    - /oauth/keys
    - /error
    - /login
    - /user/getCurrentUser

